In [1]:
import pandas as pd
import numpy as np

Loading the dataset saved in the previous exercise

In [2]:
df_post = pd.read_csv('Toronto.csv', index_col=0)
df_post

    Postcode      Borough                                      Neighbourhood
0        M1B  Scarborough                                     Rouge, Malvern
1        M1C  Scarborough             Highland Creek, Rouge Hill, Port Union
2        M1E  Scarborough                  Guildwood, Morningside, West Hill
3        M1G  Scarborough                                             Woburn
4        M1H  Scarborough                                          Cedarbrae
..       ...          ...                                                ...
98       M9N         York                                             Weston
99       M9P    Etobicoke                                          Westmount
100      M9R    Etobicoke  Kingsview Village, Martin Grove Gardens, Richv...
101      M9V    Etobicoke  Albion Gardens, Beaumond Heights, Humbergate, ...
102      M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

Create two columns

In [3]:
df_post['Latitude'] = np.nan
df_post['Longitude'] = np.nan
df_post

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",NaN,NaN
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",NaN,NaN
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",NaN,NaN
3,M1G,Scarborough,Woburn,NaN,NaN
4,M1H,Scarborough,Cedarbrae,NaN,NaN
...,...,...,...,...,...
98,M9N,York,Weston,NaN,NaN
99,M9P,Etobicoke,Westmount,NaN,NaN
100,M9R,Etobicoke,"Kingsview Village, Martin Grove Gardens, Richv...",NaN,NaN
101,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ...",NaN,NaN
102,M9W,Etobicoke,Northwest,NaN,NaN

Install the geocoder

In [4]:
!pip install geocoder

Requirement already satisfied: geocoder in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (1.38.1)
Requirement already satisfied: click in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from geocoder) (7.0)
Requirement already satisfied: ratelim in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from geocoder) (0.1.6)
Requirement already satisfied: requests in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from geocoder) (2.23.0)
Requirement already satisfied: future in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from geocoder) (0.18.2)
Requirement already satisfied: six in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from geocoder) (1.14.0)
Requirement already satisfied: decorator in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from ratelim->geocoder) (4.4.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from requests->geocoder) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from requests->geocoder) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from requests->geocoder) (1.25.8)

Function to get the coodinates

In [5]:
import geocoder # import geocoder

def getCoordinates(code):
    # initialize your variable to None
    lat_lng_coords = None
    count = 0;
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        count = count+1
        if count > 10:
            print('More than 10 attempts')
            return 0,0
        g = geocoder.google('Downtown Toronto, Toronto, Ontario')
        lat_lng_coords = g.latlng
    latitude = lat_lng_coords[0]
    longitude = lat_lng_coords[1]
    return latitude,longitude

Iterate through all the postcodes

In [6]:
lats=[]
longs=[]
for i, row in df_post.iterrows():
    print(row['Postcode'])
    code = row['Postcode']
    latitude,longitude = getCoordinates(code)
    if latitude==0:
        lats.append(0)
        longs.append(0)
    else:
        lats.append(latitude)
        row.append(longitude)

M1B
More than 10 attempts
M1C
More than 10 attempts
M1E
More than 10 attempts
M1G
More than 10 attempts
M1H
More than 10 attempts
M1J
More than 10 attempts
M1K
More than 10 attempts
M1L
More than 10 attempts
M1M
More than 10 attempts
M1N
More than 10 attempts
M1P
More than 10 attempts
M1R
More than 10 attempts
M1S
More than 10 attempts
M1T
More than 10 attempts
M1V
More than 10 attempts
M1W
More than 10 attempts
M1X
More than 10 attempts
M2H
More than 10 attempts
M2J
More than 10 attempts
M2K
More than 10 attempts
M2L
More than 10 attempts
M2M
More than 10 attempts
M2N
More than 10 attempts
M2P
More than 10 attempts
M2R
More than 10 attempts
M3A
More than 10 attempts
M3B
More than 10 attempts
M3C
More than 10 attempts
M3H
More than 10 attempts
M3J
More than 10 attempts
M3K
More than 10 attempts
M3L
More than 10 attempts
M3M
More than 10 attempts
M3N
More than 10 attempts
M4A
More than 10 attempts
M4B
More than 10 attempts
M4C
More than 10 attempts
M4E
More than 10 attempts
M4G
More than 10 attempts
M4H
More than 10 attempts
M4J
More than 10 attempts
M4K
More than 10 attempts
M4L
More than 10 attempts
M4M
More than 10 attempts
M4N
More than 10 attempts
M4P
More than 10 attempts
M4R
More than 10 attempts
M4S
More than 10 attempts
M4T
More than 10 attempts
M4V
More than 10 attempts
M4W
More than 10 attempts
M4X
More than 10 attempts
M4Y
More than 10 attempts
M5A
More than 10 attempts
M5B
More than 10 attempts
M5C
More than 10 attempts
M5E
More than 10 attempts
M5G
More than 10 attempts
M5H
More than 10 attempts
M5J
More than 10 attempts
M5K
More than 10 attempts
M5L
More than 10 attempts
M5M
More than 10 attempts
M5N
More than 10 attempts
M5P
More than 10 attempts
M5R
More than 10 attempts
M5S
More than 10 attempts
M5T
More than 10 attempts
M5V
More than 10 attempts
M5W
More than 10 attempts
M5X
More than 10 attempts
M6A
More than 10 attempts
M6B
More than 10 attempts
M6C
More than 10 attempts
M6E
More than 10 attempts
M6G
More than 10 attempts
M6H
More than 10 attempts
M6J
More than 10 attempts
M6K
More than 10 attempts
M6L
More than 10 attempts
M6M
More than 10 attempts
M6N
More than 10 attempts
M6P
More than 10 attempts
M6R
More than 10 attempts
M6S
More than 10 attempts
M7A
More than 10 attempts
M7R
More than 10 attempts
M7Y
More than 10 attempts
M8V
More than 10 attempts
M8W
More than 10 attempts
M8X
More than 10 attempts
M8Y
More than 10 attempts
M8Z
More than 10 attempts
M9A
More than 10 attempts
M9B
More than 10 attempts
M9C
More than 10 attempts
M9L
More than 10 attempts
M9M
More than 10 attempts
M9N
More than 10 attempts
M9P
More than 10 attempts
M9R
More than 10 attempts
M9V
More than 10 attempts
M9W
More than 10 attempts

# Geocode isn't working! So I am using pgeocode
I prefered to do this instead of loading the file http://cocl.us/Geospatial_data

In [7]:
pip install pgeocode

Requirement already satisfied: pgeocode in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (0.2.1)
Requirement already satisfied: pandas in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from pgeocode) (1.0.1)
Requirement already satisfied: requests in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from pgeocode) (2.23.0)
Requirement already satisfied: numpy in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from pgeocode) (1.18.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from pandas->pgeocode) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from pandas->pgeocode) (2019.3)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from requests->pgeocode) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from requests->pgeocode) (2019.11.28)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from requests->pgeocode) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from requests->pgeocode) (2.9)
Requirement already satisfied: six>=1.5 in /home/mateus/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->pgeocode) (1.14.0)
Note: you may need to restart the kernel to use updated packages.

Geocode is working, but it acept only the postcode in the query string.

In [8]:
import pgeocode
nomi = pgeocode.Nominatim('ca')
lats=[]
longs=[]
for i, row in df_post.iterrows():
    print(row['Postcode'])
    code = row['Postcode']
    location = nomi.query_postal_code(code)
    print(location.latitude, location.longitude)
    lats.append(location.latitude)
    longs.append(location.longitude)

M1B
43.8113 -79.193
M1C
43.7878 -79.1564
M1E
43.7678 -79.1866
M1G
43.7712 -79.2144
M1H
43.7686 -79.2389
M1J
43.7464 -79.2323
M1K
43.7298 -79.2639
M1L
43.7122 -79.2843
M1M
43.7247 -79.2312
M1N
43.6952 -79.2646
M1P
43.7612 -79.2707
M1R
43.7507 -79.3003
M1S
43.7946 -79.2644
M1T
43.7812 -79.3036
M1V
43.8177 -79.2819
M1W
43.8016 -79.3216
M1X
43.834 -79.2069
M2H
43.8015 -79.3577
M2J
43.7801 -79.3479
M2K
43.7797 -79.3813
M2L
43.7547 -79.3764
M2M
43.7915 -79.4103
M2N
43.7673 -79.4111
M2P
43.75 -79.3978
M2R
43.7786 -79.445
M3A
43.7545 -79.33
M3B
43.745 -79.359
M3C
43.7334 -79.3329
M3H
43.7535 -79.4472
M3J
43.7694 -79.4921
M3K
43.739 -79.4692
M3L
43.7334 -79.5116
M3M
43.7319 -79.4928
M3N
43.7568 -79.521
M4A
43.7276 -79.3148
M4B
43.7063 -79.3094
M4C
43.6913 -79.3116
M4E
43.6784 -79.2941
M4G
43.7124 -79.3644
M4H
43.7059 -79.3464
M4J
43.6872 -79.3368
M4K
43.6803 -79.3538
M4L
43.6693 -79.3155
M4M
43.6561 -79.3406
M4N
43.7301 -79.3935
M4P
43.7135 -79.3887
M4R
43.7143 -79.4065
M4S
43.702 -79.3853
M4T
43.6899 -79.3853
M4V
43.6861 -79.4025
M4W
43.6827 -79.373
M4X
43.6684 -79.3689
M4Y
43.6656 -79.383
M5A
43.6555 -79.3626
M5B
43.6572 -79.3783
M5C
43.6513 -79.3756
M5E
43.6456 -79.3754
M5G
43.6564 -79.38600000000002
M5H
43.6496 -79.3833
M5J
43.62300000000001 -79.3936
M5K
43.6469 -79.3823
M5L
43.6492 -79.3823
M5M
43.7335 -79.4177
M5N
43.7113 -79.4195
M5P
43.6966 -79.41199999999998
M5R
43.6736 -79.4035
M5S
43.6629 -79.3987
M5T
43.6541 -79.3978
M5V
43.6404 -79.3995
M5W
43.6437 -79.3787
M5X
43.6492 -79.3823
M6A
43.7223 -79.4504
M6B
43.7081 -79.4479
M6C
43.6915 -79.4307
M6E
43.6889 -79.4507
M6G
43.6683 -79.4205
M6H
43.6655 -79.4378
M6J
43.648 -79.4177
M6K
43.6383 -79.4301
M6L
43.7137 -79.4869
M6M
43.6934 -79.4857
M6N
43.6748 -79.4839
M6P
43.6605 -79.4633
M6R
43.6469 -79.4521
M6S
43.6512 -79.4828
M7A
43.6641 -79.3889
M7R
nan nan
M7Y
43.7804 -79.2505
M8V
43.6075 -79.5013
M8W
43.6021 -79.5402
M8X
43.6518 -79.5076
M8Y
43.6325 -79.4939
M8Z
43.6256 -79.5231
M9A
43.6662 -79.5282
M9B
43.6505 -79.5517
M9C
43.6437 -79.5767
M9L
43.7598 -79.5565
M9M
43.7366 -79.5401
M9N
43.7068 -79.517
M9P
43.6949 -79.5323
M9R
43.6898 -79.5582
M9V
43.7432 -79.5876
M9W
43.7144 -79.5909

Insert the latitudes and longitudes in the df_post

In [12]:
df_post['Latitude']=lats
df_post['Longitude']=longs

In [13]:
df_post

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.8113,-79.1930
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.7878,-79.1564
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.7678,-79.1866
3,M1G,Scarborough,Woburn,43.7712,-79.2144
4,M1H,Scarborough,Cedarbrae,43.7686,-79.2389
...,...,...,...,...,...
98,M9N,York,Weston,43.7068,-79.5170
99,M9P,Etobicoke,Westmount,43.6949,-79.5323
100,M9R,Etobicoke,"Kingsview Village, Martin Grove Gardens, Richv...",43.6898,-79.5582
101,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ...",43.7432,-79.5876
102,M9W,Etobicoke,Northwest,43.7144,-79.5909

In [14]:
#Save dataset to .csv 
df_post.to_csv('Toronto_2.csv')

In [16]:
df_post.shape

(103, 5)